/** Default game state for new accounts — mirrors client defaults. */
import type { GameStatePayload } from './types.js'

export function defaultGameState(): GameStatePayload {
  return {
    portfolio: {
      cash: 100_000,
      holdings: [],
      orders: [],
      watchlist: ['AAPL', 'NVDA', 'MSFT'],
      alerts: [],
      marginLoan: 0,
    },
    progress: {
      xp: 0,
      level: 1,
      quests: [],
      achievements: [],
      streak: 1,
      lastVisitDate: new Date().toISOString().slice(0, 10),
      stats: {
        totalTrades: 0,
        buyOrders: 0,
        sellOrders: 0,
        limitOrders: 0,
        watchlistAdds: 0,
        sectorsHeld: 0,
        bestProfitPct: 0,
        portfolioPeak: 100_000,
        sectorSprintScore: 0,
        compareToolUsed: false,
        positionSizerUsed: false,
        holdingsCountMax: 0,
        chartRangesUsed: [],
        flashQuotesBest: 0,
        tradesThisWeek: 0,
        weekTradeKey: new Date().toISOString().slice(0, 10),
        quizzesThisWeek: 0,
        quizWeekKey: new Date().toISOString().slice(0, 10),
        sprintsThisWeek: 0,
        sprintWeekKey: new Date().toISOString().slice(0, 10),
        predictorWinsThisWeek: 0,
        predictorWeekKey: new Date().toISOString().slice(0, 10),
        dayStartValue: 100_000,
        dayStartDate: new Date().toISOString().slice(0, 10),
        largestSingleLoss: 0,
        marginUsed: false,
        liquidationCount: 0,
      },
      dailyBonusDate: null,
      weeklyChallengeWeek: null,
      weeklyChallengeId: null,
      weeklyChallengeDone: false,
      dailyQuestId: 'daily-trade-2',
      dailyQuestDate: new Date().toISOString().slice(0, 10),
      quizzesPassed: [],
      scenariosCompleted: 0,
      predictionsWon: 0,
      predictionsTotal: 0,
      tabsVisited: [],
      toastQueue: [],
      lastSprintDate: null,
      positionSizerUses: 0,
      profile: { accentId: 'teal', motto: '' },
    },
  }
}
